random_seed: 444

dataset:
  type: &dataset_type "KITTI"
  source_dataset_name: "carla" # 'kitti', 'tum', 'carla'
  target_dataset_name: "tum" # 'kitti', 'tum', 'carla'
  source_root_dir: "/data/carla_dataset_large"
  target_root_dir: "/data/s110_o_dataset/"
  # target_root_dir: "/data/tum_traffic_snow"
  target_eval_root_dir: "/data/s110_o_dataset/"
  train_split: "train"
  test_split: &test_split "val"
  batch_size: 8
  use_3d_center: True
  class_merging: False
  use_dontcare: False
  bbox2d_type: "anno" # 'proj' or 'anno'
  meanshape: False # use predefined anchor or not
  # writelist: ['Car','Pedestrian', 'Cyclist',
  #                          'Van', 'Truck', 'Bus', 'Motorcycle', 'Trailer']
  writelist: ["Car", "Pedestrian", "Cyclist",  'Van', 'Bus', "BigCar"]
  clip_2d: False

  aug_pd: True
  aug_crop: True

  random_flip: 0.5
  random_crop: 0.5
  scale: 0.05
  shift: 0.05

  depth_scale: "normal"


  # Camera extrinsics 
  s110_s_extrinsic: [[0.8908996710592079, 0.4539106721758699, -0.01621350645128411, 14.9101040410128], [0.14348498713003754, -0.31513083494486965, -0.9381389104686164, 11.942959999763062], [-0.4309406392705249, 0.8334612519798386, -0.34587932414833933, -7.259570302320384], [0.0, 0.0, 0.0, 1.0]]
  s110_o_extrinsic: [[-0.9791943067183705,-0.20243228170165417,-0.01413085331436903,-14.86237426802586],[-0.07949385649148555,0.4467289911774407,-0.8911307060256075,5.081140416221899],[0.18670628396077432,-0.8714667978567219,-0.45352660755782637,7.648446136603923],[0.0,0.0,0.0,1.0]]
  s110_w_extrinsic:  [[0.9868669754034978,0.1613870750363431,0.00691266006440161,1.4891242696353402],[0.08242702564383086,-0.4663075869422193,-0.880774102595913,8.244394009061523],[-0.1389221303517314,0.8697766646509542,-0.47348621450597506,3.172645642076077],[0.0,0.0,0.0,1.0]]
  s110_n_extrinsic: [[0.636759821687839, -0.771052609811788, -0.003847386970684874, -0.5992114968785813], [-0.4453066645159012, -0.36366580126620224, -0.8181987286271801, 8.05072755513902], [0.6294751019871989, 0.5227093436048773, -0.5749226366097999, 4.171119732791681], [0.0, 0.0, 0.0, 1.0]]


model_name: &model_name "warm3d_6class_on4cam_3_withoutextrinsicloss_withoutplaneloss_without2D3Dconst_GTGroundpitchroll_0.99Keeprate_noextrincsloss"
model:
  model_name: *model_name
  num_classes: 6
  return_intermediate_dec: True
  device: "cuda"

  # Backbone
  backbone: "resnet50"
  train_backbone: True
  num_feature_levels: 4
  dilation: False
  position_embedding: "sine" # 'sine' or 'learned'
  masks: False

  # Depth predictor
  mode: LID
  num_depth_bins: 80
  depth_min: 1e-3
  depth_max: 120.0

  # Transformer
  with_box_refine: True
  two_stage: False
  use_dab: False
  use_dn: False
  use_target_dn: False
  two_stage_dino: False
  init_box: False
  enc_layers: 3
  dec_layers: 3
  hidden_dim: 256
  dim_feedforward: 256
  dropout: 0.1
  nheads: 8
  num_queries: 50
  enc_n_points: 4
  dec_n_points: 4

  # DN
  scalar: 5
  label_noise_scale: 0.2
  box_noise_scale: 0.4
  num_patterns: 0

  # Loss
  aux_loss: True
  target_aux_loss: true

  # Loss coefficients
  cls_loss_coef: 2
  focal_alpha: 0.25
  bbox_loss_coef: 5
  giou_loss_coef: 2
  3dcenter_loss_coef: 10
  dim_loss_coef: 1
  angle_loss_coef: 1
  depth_loss_coef: 1
  depth_map_loss_coef: 1
  feature_extrinsic_loss_coef: 1

  #Target loss coefficients
  target_cls_loss_coef: 2
  target_bbox_loss_coef: 5
  target_giou_loss_coef: 2
  target_dim_loss_coef: 1
  target_angle_loss_coef: 1
  target_depth_loss_coef: 1
  target_3dcenter_loss_coef: 10
  target_depth_map_loss_coef: 1
  target_constraint_loss_coef: 10
  target_feature_extrinsic_loss_coef: 1
  target_extrinsic_loss_coef: 1

  # Matcher
  set_cost_class: 2
  set_cost_bbox: 5
  set_cost_giou: 2
  set_cost_3dcenter: 10

optimizer:
  type: "adamw"
  lr: 0.0001
  weight_decay: 0.0001

lr_scheduler:
  type: "step" # 'step' or 'cos'
  warmup: False # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.1
  # decay_list: [125, 165]
  decay_list: [125, 165]
  burn_in_decay_list: [20, 40]

trainer:
  burn_in_max_epoch: 50
  max_epoch: 20 #195
  gpu_ids: "0"
  save_frequency: 1 # checkpoint save interval (in epoch)
  ema_update_frequency: 1 # EMA update interval (in epoch)
  keep_rate: 0.99
  ema_step: 200
  # resume_model: True
  # pretrain_model: path/to/ckpt
  burned_in_teacher: "/workspace/MonoDETR/outputs/warm3d_carla_baseline_6class/checkpoint_best.pth"
  # burned_in_teacher: "/workspace/MonoDETR/outputs/monodetr_bl_carla_large_ext_vis_depth_MLP/checkpoint_best.pth"
  # burned_in_teacher: "/workspace/MonoDETR/outputs/warm3d_4class_4cam/student_checkpoint.pth"
  # burned_in_teacher: "/workspace/MonoDETR/outputs/warm3d_4class_4cam_1/teacher_checkpoint_epoch_5.pth"

  save_path: "outputs/"
  save_all: True # False for only savng the best and latest ckpts
  use_dn: False
  scalar: 5
  label_noise_scale: 0.2
  box_noise_scale: 0.4
  num_patterns: 0
  threshold_increase_list: 0.3

  wandb_log: &wandb True
  wandb_project: *model_name

tester:
  type: *dataset_type
  mode: single # 'single' or 'all'; 'all' to evaluate all ckpts in the folder
  checkpoint: 40 # the start ckpt epoch for 'all'
  threshold: 0.35 # confidence filter
  topk: 50
  test_split: *test_split

  wandb_log: *wandb
